### ISSUE TITLE
Icon change on copying URL

### ISSUE THREAD

**Issue by smaragdus** [vantezzen/Quick-Copy-URL#1]
On copying URL [Quick Copy URL](https://github.com/vantezzen/quick-copy-url) may change icon colour for a second or show 'OK' badge on icon. This will serve as a confirmation that the URL was copied.

**Comment by vantezzen** [comment]
Thank you for this request. I added this feature with v1.1

**Comment by smaragdus** [comment]
@vantezzen 

Nice implementation, thanks!
