### ISSUE TITLE
No copy on no https urls

### ISSUE THREAD

**Issue by guest73** [vantezzen/Quick-Copy-URL#4]
I have a bunch of urls served on my VPN which are not https urls. I cannot copy those. The urls are from our local JIRA, NEXUS, Jenkins ect which I copy a lot for sharing. Without an ability to copy regular urs the plugin becomes pretty much useless for me :(. Is it possible to do anything about it?

**Comment by vantezzen** [comment]
Fixed in 1.3 which should be available soon - I uploaded it to the addon stores but it may need a few days until they publish it.
